#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour";
    minute=1;
    while [ $minute -lt 60 ]
    do
        echo "$minute";
        minute=$((minute + 1));
    done
    hour=$((hour + 1))
done
