#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

for i in *
do
    echo "$i" | cut -d '-' -f 2;
done
